---
deployment:
  tasks:
    - export DEPLOYPATH=/home/busnisscard/public_html/platform
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .[!.]* $DEPLOYPATH
    - cd $DEPLOYPATH
    - /opt/cpanel/ea-php84/root/usr/bin/php artisan storage:link --force
