---
deployment:
  tasks:
    - export DEPLOYPATH=/home/busnisscard/public_html/fitness-platform
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .[!.]* $DEPLOYPATH
    - cd $DEPLOYPATH
    - php artisan storage:link --force
